/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao;

import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import javax.swing.JTable;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import br.com.controle.BuscaExcell;
import br.com.controle.Turma;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static jxl.CellReferenceHelper.getColumn;
import static jxl.biff.CellReferenceHelper.getColumn;
import jxl.read.biff.BiffException;

/**
 *
 * @author User
 */
public class JFimporta extends javax.swing.JFrame {

    /**
     * Creates new form JFimporta
     */
    public JFimporta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTabdados1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabdados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabdados2 = new javax.swing.JTable();
        jBlistar = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        jTabdados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "Turma", "Disciplina", "Nome", "Nota1", "Nota2", "Media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTabdados1);
        if (jTabdados1.getColumnModel().getColumnCount() > 0) {
            jTabdados1.getColumnModel().getColumn(0).setResizable(false);
            jTabdados1.getColumnModel().getColumn(0).setPreferredWidth(3);
            jTabdados1.getColumnModel().getColumn(1).setResizable(false);
            jTabdados1.getColumnModel().getColumn(2).setResizable(false);
            jTabdados1.getColumnModel().getColumn(3).setResizable(false);
            jTabdados1.getColumnModel().getColumn(4).setResizable(false);
            jTabdados1.getColumnModel().getColumn(5).setResizable(false);
            jTabdados1.getColumnModel().getColumn(6).setResizable(false);
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("importa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabdados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "Turma", "Disciplina", "Nome", "Nota1", "Nota2", "Media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabdados);
        if (jTabdados.getColumnModel().getColumnCount() > 0) {
            jTabdados.getColumnModel().getColumn(0).setResizable(false);
            jTabdados.getColumnModel().getColumn(0).setPreferredWidth(3);
            jTabdados.getColumnModel().getColumn(1).setResizable(false);
            jTabdados.getColumnModel().getColumn(2).setResizable(false);
            jTabdados.getColumnModel().getColumn(3).setResizable(false);
            jTabdados.getColumnModel().getColumn(4).setResizable(false);
            jTabdados.getColumnModel().getColumn(5).setResizable(false);
            jTabdados.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setText("Média total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Média TADS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Média 2AM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Média SI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Média 3AM");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Média 4AM");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Média LTPI");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Média LTPII");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Média PHP");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Média BANCO");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTabdados2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Curso", "Turma", "Disciplina", "Nome", "Nota1", "Nota2", "Media"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabdados2);
        if (jTabdados2.getColumnModel().getColumnCount() > 0) {
            jTabdados2.getColumnModel().getColumn(0).setResizable(false);
            jTabdados2.getColumnModel().getColumn(0).setPreferredWidth(3);
            jTabdados2.getColumnModel().getColumn(1).setResizable(false);
            jTabdados2.getColumnModel().getColumn(2).setResizable(false);
            jTabdados2.getColumnModel().getColumn(3).setResizable(false);
            jTabdados2.getColumnModel().getColumn(4).setResizable(false);
            jTabdados2.getColumnModel().getColumn(5).setResizable(false);
            jTabdados2.getColumnModel().getColumn(6).setResizable(false);
        }

        jBlistar.setText("jButton12");
        jBlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistarActionPerformed(evt);
            }
        });

        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(216, 216, 216)
                        .addComponent(jBlistar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jBlistar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BuscaExcell bx = new BuscaExcell();
        Turma t1 = new Turma();
   
     DefaultTableModel tabelaResultado = (DefaultTableModel) jTabdados.getModel();
      ArrayList<Turma> ctdados = null;  
        try {
            ctdados = bx.rodar();
              for (int i = 0; i < ctdados.size(); i++) {                
                t1 = ctdados.get(i);
               tabelaResultado.addRow(new Object[]{t1.getCurso(),t1.getTurma(),t1.getDisciplina(),t1.getNome(),
              t1.getNota1(),t1.getNota2()});
        }
        } catch (IOException ex) {
            Logger.getLogger(JFimporta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(JFimporta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFimporta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFimporta.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
        //jLabel1.setText(t1.media().toString());
          
        
        //jLabel1.setText(t1.media().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        double total = 0;
        double md=0;
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        }
        jLabel1.setText("Media Total: " + md);
        
      
               
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        double md=0;
        String curso = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        curso = String.valueOf(jTabdados.getValueAt(i, 0));//setando no campo nota1   
        if(curso.contains("TADS") == contains(i, 0) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media TADS: " + md);
        }
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                double total = 0;
        double md=0;
        String turma = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        turma = String.valueOf(jTabdados.getValueAt(i, 1));//setando no campo nota1   
        if(turma.contains("2AM") == contains(i, 1) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media 2AM: " + md);
        }
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        double md=0;
        String curso = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        curso = String.valueOf(jTabdados.getValueAt(i, 0));//setando no campo nota1   
        if(curso.contains("SI") == contains(i, 0) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media SI: " + md);
        }
      }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        double md=0;
        String turma = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        turma = String.valueOf(jTabdados.getValueAt(i, 1));//setando no campo nota1   
        if(turma.contains("3AM") == contains(i, 1) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media 3AM: " + md);
        }
      }        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        double md=0;
        String turma = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        turma = String.valueOf(jTabdados.getValueAt(i, 1));//setando no campo nota1   
        if(turma.contains("4AM") == contains(i, 1) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media 4AM: " + md);
        }
      }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        double md=0;
        String disciplina = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        disciplina = String.valueOf(jTabdados.getValueAt(i, 2));//setando no campo nota1   
        if(disciplina.contains("LTPI") == contains(i, 2) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media LTPI: " + md);
        }
      }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
                double total = 0;
        double md=0;
        String disciplina = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        disciplina = String.valueOf(jTabdados.getValueAt(i, 2));//setando no campo nota1   
        if(disciplina.contains("BANCO") == contains(i, 2) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media BANCO: " + md);
        }
      }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        double md=0;
        String disciplina = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        disciplina = String.valueOf(jTabdados.getValueAt(i, 2));//setando no campo nota1   
        if(disciplina.contains("LTPII") == contains(i, 2) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media LTPII: " + md);
        }
      }       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
                        double total = 0;
        double md=0;
        String disciplina = "";
        String valor1 = "";
        String valor2 = "";
        int qtd=0;
        int linhas = jTabdados.getRowCount();//contando as linhas da jtable
        for(int i = 0; i < linhas; i++){
        disciplina = String.valueOf(jTabdados.getValueAt(i, 2));//setando no campo nota1   
        if(disciplina.contains("PHP") == contains(i, 2) ){
        valor1 = String.valueOf(jTabdados.getValueAt(i, 4));//setando no campo nota1
        valor2 = String.valueOf(jTabdados.getValueAt(i, 5));//setando no campo nota2
        total = total + (Double.parseDouble(valor1)+Double.parseDouble(valor2));
        qtd ++;
        md=(total/qtd);
        jLabel1.setText("Media PHP: " + md);
        }
      }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistarActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tabelaResultado = (DefaultTableModel) jTabdados.getModel();
        DefaultTableModel tabelaResultado2 = (DefaultTableModel) jTabdados2.getModel();
        String disciplina = "";
        int linhas = jTabdados.getRowCount();
        
        for(int i = 0; i < linhas; i++){
            disciplina = String.valueOf(jTabdados.getValueAt(i, 2));
            if(disciplina.contains("PHP") == contains(i, 2) ){
        tabelaResultado2.addRow(new Object[]{tabelaResultado.getValueAt(i, 0),tabelaResultado.getValueAt(i, 1),tabelaResultado.getValueAt(i, 2),
        tabelaResultado.getValueAt(i, 3), tabelaResultado.getValueAt(i, 4), tabelaResultado.getValueAt(i, 5)});
        
            }
        }

    }//GEN-LAST:event_jBlistarActionPerformed

private File file;
        private List<JTable> jTabdados1;
        private List<String> nome_files;
        
            public JFimporta(File file, List<JTable> jTabdados2, List<String> nome_files) throws Exception {
        this.file = file;
        this.jTabdados1 = jTabdados1;
        this.nome_files = nome_files;
        if(nome_files.size()!=jTabdados2.size()){
            throw new Exception("Error");
        }
    }
          public boolean export(){
            try{
                DataOutputStream out=new DataOutputStream(new FileOutputStream(file));
                WritableWorkbook w=Workbook.createWorkbook(out);
                for (int index = 0; index <jTabdados1.size();index++) {
                        JTable table= jTabdados1.get(index);
                        WritableSheet s=w.createSheet(nome_files.get(index), 0);
                        for (int i = 0; i < table.getColumnCount(); i++) {
                            for (int j = 0; j < table.getRowCount(); j++) {
                                Object object=table.getValueAt(j,i);
                                s.addCell(new Label(i,j,String.valueOf(object)));
                            }
                        }
                    }
                w.write();
                w.close();
                return true;
            }
            
            catch (IOException | WriteException e){
                return false;
                }
          }
        
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (this.jTabdados2.getRowCount()==0) {
          JOptionPane.showMessageDialog(null, "Não tem dados para exportar", JOptionPane.INFORMATION_MESSAGE);
          this..grabFocus();
          
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFimporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFimporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFimporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFimporta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFimporta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlistar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabdados;
    private javax.swing.JTable jTabdados1;
    private javax.swing.JTable jTabdados2;
    // End of variables declaration//GEN-END:variables

    private boolean contains(String php) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
